spring:
  application:
    name: notification-service
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 8383
eureka:
  instance:
    hostname: ${SERVICE_HOST:localhost}
  client:
    serviceUrl:
      defaultZone : http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  server:
    eviction-interval-timer-in-ms: 1000

security:
  basic:
    enabled: false
  oauth2:
    resource:
      token-info-uri: http://authentication-service/oauth/check_token
    client:
      client-id: javadeveloperzone
      client-secret: secret
