eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/
  server:
    eviction-interval-timer-in-ms: 10000

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
        - id: AUTHENTICATION-SERVICE
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**
        - id: USER-SERVICE
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/users/**
        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
        - id: SHOP-SERVICE
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/shops/**
        - id: MENU-SERVICE
          uri: lb://MENU-SERVICE
          predicates:
            - Path=/menus/**
logging:
  level:
    root: DEBUG