version: '3.9'

services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=digital_coffee
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=digital_coffee
    ports:
      - "5432:5432"
    volumes:
      - ./init_postgres/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  solace:
    image: solace/solace-pubsub-standard:latest
    shm_size: 1g
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1
    ports:
      - 55554:55554
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
      - system_scaling_maxconnectioncount=100

volumes:
  db:
    driver: local