version: '3.9'

services:
  db-user:
    image: postgres:14.11
    restart: always
    environment:
      POSTGRES_DB: digital_coffee
      POSTGRES_USER: digital_coffee
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5433'
    volumes:
      - db:/var/lib/postgresql/data
  db-shop:
    image: postgres:14.11
    restart: always
    environment:
      POSTGRES_DB: digital_coffee
      POSTGRES_USER: digital_coffee
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5434'
    volumes:
      - db:/var/lib/postgresql/data
  db-menu:
    image: postgres:14.11
    restart: always
    environment:
      POSTGRES_DB: digital_coffee
      POSTGRES_USER: digital_coffee
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5435'
    volumes:
      - db:/var/lib/postgresql/data
  db-order:
    image: postgres:14.11
    restart: always
    environment:
      POSTGRES_DB: digital_coffee
      POSTGRES_USER: digital_coffee
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5436'
    volumes:
      - db:/var/lib/postgresql/data
  db-customer:
    image: postgres:14.11
    restart: always
    environment:
      POSTGRES_DB: digital_coffee
      POSTGRES_USER: digital_coffee
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5437'
    volumes:
      - db:/var/lib/postgresql/data

  solace:
    image: solace/solace-pubsub-standard:latest
    shm_size: 1g
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1
    ports:
      - 55554:55554
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
      - system_scaling_maxconnectioncount=100

volumes:
  db:
    driver: local