eureka:
  instance:
    hostname: ${SERVICE_HOST:localhost}
  client:
    serviceUrl:
      defaultZone : http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  server:
    eviction-interval-timer-in-ms: 1000

spring:
  application:
    name: user-service
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/user_db"
    username: digital_coffee
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          create_namespaces: true
  flyway:
    enabled: true # enable Flyway

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

server:
  port: 8484

logging:
  level:
    root: INFO

