spring:
  application:
    name: user-service
  datasource:
    url: "jdbc:postgresql://localhost:5432/user_db"
    username: digital_coffee
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          create_namespaces: true
  flyway:
    enabled: true # enable Flyway

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

server:
  port: 8484
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/

logging:
  level:
    root: INFO
