eureka:
  instance:
    hostname: ${SERVICE_HOST:localhost}
  client:
    serviceUrl:
      defaultZone : http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
        - id: SHOP-SERVICE
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/shops/**
        - id: MENU-SERVICE
          uri: lb://MENU-SERVICE
          predicates:
            - Path=/menus/**
logging:
  level:
    root: INFO