server:
  port: 8761

eureka:
  instance:
    hostname: ${SERVICE_HOST:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone : http://${SERVICE_HOST}:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 1000
